name: 'Setup HOA Majors CLI'
description: 'Install the HOA Majors CLI tool and its dependencies using uv'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.14'
  uv-version:
    description: 'uv version to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: ${{ inputs.uv-version }}
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - name: Install HOA Majors CLI
      run: |
        uv pip install "${{ github.action_path }}"
      shell: bash
